name: dsl2020-ppis
channels: 
   - defaults
dependencies:
   - python>=3.7
   - jupyter
   - matplotlib 
   - pandas
   - numpy
   - scikit-learn
   - seaborn
   - tqdm
   - pip>=20.0
   - networkx
   - urllib
   


   

